name: "SonarQube Scan"
description: "Run SonarQube scan."
inputs:
  project_key:
    description: "Sonar project key"
    required: true
  project_name:
    description: "Sonar project name"
    required: true
  host_url:
    description: "SonarQube host URL"
    required: true
  token:
    description: "Sonar token"
    required: true
  extra_args:
    description: "Extra args for scanner"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      env:
        SONAR_HOST_URL: ${{ inputs.host_url }}
        SONAR_TOKEN: ${{ inputs.token }}
      with:
        args: >
          -Dsonar.projectKey=${{ inputs.project_key }}
          -Dsonar.projectName=${{ inputs.project_name }}
          ${{ inputs.extra_args }}
