name: "Docker Build and Push"
description: "Build and push a multi-arch Docker image."
inputs:
  registry:
    description: "Registry host"
    required: false
    default: "docker.io"
  username:
    description: "Registry username"
    required: true
  password:
    description: "Registry password or token"
    required: true
  image_name:
    description: "Image name"
    required: true
  context:
    description: "Build context"
    required: false
    default: "."
  dockerfile:
    description: "Dockerfile path"
    required: false
    default: "Dockerfile"
  tags:
    description: "Comma-separated tags"
    required: false
    default: "latest"
  platforms:
    description: "Target platforms"
    required: false
    default: "linux/amd64,linux/arm64"
  build_args:
    description: "Multiline build args"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.image_name }}:${{ inputs.tags }}
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build_args }}
        push: true
