name: "Checkov Scan"
description: "Run Checkov on IaC."
inputs:
  directory:
    description: "Directory to scan"
    required: false
    default: "."
  soft_fail:
    description: "Soft fail"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: ${{ inputs.directory }}
        soft_fail: ${{ inputs.soft_fail }}
